### PR TITLE
Add linter package

### PR DESCRIPTION
**Pull request by dertseha**
This PR adds the linter package `golangci-lint` with many linters enabled and adapted for. Also included is a GitHub action to run them automatically.
Motivation for this is to allow adherence to established standards for a critical library.

I've marked some linters as highly recommended, yet didn't include them yet as they need domain experts and/or a dedicated discussion. I'll create separate issues for those.

Most notable changes include the removal of some unused code and some minor changes to the code (in terms of usage of the language). During all of this the tests, both functional and for benchmarks, remained satisfied.

### CODE REVIEW

**Comment by dertseha** [comment]
I've resolved all the merge conflicts that came from the recent updates.

To clarify: Are you interested in a linter package? Because keeping a PR in line with changes needs extra effort.
Please tell if you do want to add this, or if you are objecting to (some of) the linters.

**Comment by AnomalRoil** [comment]
Definitively a must have in my opinion :) 

Thank you for all the work, we just haven't had time to wrap our head about reviewing all the changes. It might have been easier to "just" add the linter action and let us do the required code changes to pass it.

Since this is crypto code, we need to carefully review all changes, even if from what I've seen it seems you've just renamed a couple variables and corrected things so that the linter won't complain.

**Comment by dertseha** [comment]
Thank you for your answer. It could go either way - simply adding the linter settings and cause hundreds of warnings might not be considered nice either :)
Because it is all about security, I did only focus on "safe" refactorings, and I let myself rely by the tests that you have.
The larger topics (error/API design) I left out for now.

**Comment by dertseha** [comment]
Closing this one in favor to the smaller one.

**Pull request closed without merging**
